name: Build Docs

on:
  workflow_run:
    workflows: ["Publish Artifacts"]
    types:
      - completed

  push:
    branches:
      - develop

jobs:
  build-docs:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.ref == 'refs/heads/develop' }}
    steps:
      - name: Trigger RTDs Build
        uses: dfm/rtds-action@v1
        with:
          webhook_url: ${{ secrets.RTDS_WEBHOOK_URL }}
          webhook_token: ${{ secrets.RTDS_WEBHOOK_TOKEN }}
          commit_ref: ${{ github.ref }}
