name: Build Wheels

on:
  push:
    tags:
      - '*'

jobs:
  deploy:
    runs-on: ubuntu-latest
    container:
      image: quay.io/pypa/manylinux2014_x86_64:latest
    env:
      PYTHON: python3.9
      PY_TARGETS: cp37-cp37m,cp38-cp38,cp39-cp39,cp310-cp310

    steps:
      - uses: actions/checkout@v2

      - name: Install Dependencies
        run: |
          set -e

          yum install -y zlib-devel lz4-devel uchardet-devel
          $PYTHON -m pip install --upgrade pip
          $PYTHON -m pip install cython twine

      - name: Build Packages
        run: |
          set -e

          for pkg in resiliparse fastwarc; do
            BUILD_PACKAGES=${pkg} $PYTHON setup.py sdist

            for py in $(eval ls -d "/opt/python/{$PY_TARGETS}/bin/python"); do
              BUILD_PACKAGES=${pkg} ${py} setup.py bdist_wheel
              rm -rf build
            done
          done

          find dist -type f -name '*-linux*.whl' -exec auditwheel repair -w dist --plat manylinux2014_x86_64 {} \;

      - name: Publish FastWARC
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_FASTWARC_API_TOKEN }}
        run: |
          $PYTHON -m twine upload dist/FastWARC-*-manylinux*.whl dist/FastWARC-*.tar.gz

      - name: Publish Resiliparse
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_RESILIPARSE_API_TOKEN }}
        run: |
          $PYTHON -m twine upload dist/Resiliparse-*-manylinux*.whl dist/Resiliparse-*.tar.gz
